[balancing]
	#How much should a fluid node transfer? (Also applies to chemical nodes if Mekanism is installed)
	# Default: 50
	# Range: 1 ~ 1000000
	fluidNodeTransfer = 50
	#How much should an essence node transfer? (Applies to all essence node types)
	# Default: 50
	# Range: 1 ~ 1000000
	essenceNodeTransfer = 50
	#How much should an item node transfer?
	# Default: 4
	# Range: 1 ~ 64
	itemNodeTransfer = 4
	#How much should an essence battery hold? (Applies to all essence battery types)
	# Default: 10000
	# Range: 1 ~ 1000000
	essenceBatteryMax = 10000
	#How much wires should nodes be able to have? (Applies to all nodes)
	# Default: 4
	# Range: 1 ~ 50
	maxNodeWires = 4
	#How many ticks should a plant with the low_essence_plant tag last in the Industrial Plant Siphon? (total Essence produced is 2.0x this value)
	# Default: 10.0
	# Range: 0.0 ~ 1000.0
	lowValuePlantEssence = 10.0
	#How many ticks should a plant with the medium_essence_plant tag last in the Industrial Plant Siphon? (total Essence produced is 4.0x this value)
	# Default: 50.0
	# Range: 0.0 ~ 1000.0
	mediumValuePlantEssence = 50.0
	#How many ticks should a plant with the high_essence_plant tag last in the Industrial Plant Siphon? (total Essence produced is 8.0x this value)
	# Default: 100.0
	# Range: 0.0 ~ 1000.0
	highValuePlantEssence = 100.0
