#When a boss has no target, should it be cleared?
boss_clear_when_no_target = true
#Multiplier for boss attributes health.
# Default: 1.0
# Range: 0.0625 ~ 10.0
boss_attributes_multiplier_health = 1.0
#Multiplier for boss attributes damage.
# Default: 1.0
# Range: 0.0625 ~ 10.0
boss_attributes_multiplier_damage = 1.0
#Should the boss have no physics? Only for some bosses.
boss_no_physics = true
#Should the boss leave on day? Only for some bosses.
boss_leave_on_day = false
#Should all monsters be enhanced?
#If false, only specific monsters in this mod.
enhance_all_monster = false
#Multiplier for monster attributes health.
# Default: 1.0
# Range: 0.0625 ~ 100.0
monster_attributes_multiplier_health = 1.0
#Multiplier for monster attributes damage.
# Default: 1.0
# Range: 0.0625 ~ 100.0
monster_attributes_multiplier_damage = 1.0
